[versions]
agp = "8.13.0"
androidxActivity = "1.11.0"
androidxAppCompat = "1.7.1"
androidxCompose = "1.9.3"
androidxCore = "1.17.0"
androidxFragment = "1.8.9"
androidxLifecycle = "2.9.4"
androidxWork = "2.10.5"
anvil = "2.7.0"
constraintlayout = "2.2.1"
dagger = "2.57.2"
kotlin = "2.2.20"
mavenPublish = "0.34.0"
autoService = "1.1.1"
detekt = "1.23.8"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
material = "1.13.0"

[plugins]
androidApp = { id = "com.android.application", version.ref = "agp" }
androidLib = { id = "com.android.library", version.ref = "agp" }
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
binaryValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinSam = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidxActivity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidxAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidxComposeMaterial = { module = "androidx.compose.material:material", version.ref = "androidxCompose" }
androidxComposeRuntime = { module = "androidx.compose.runtime:runtime", version.ref = "androidxCompose" }
androidxComposeUi = { module = "androidx.compose.ui:ui", version.ref = "androidxCompose" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxFragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidxLifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidxLifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidxLifecycleSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidxLifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidxLifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidxWorkRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWork" }
anvilAnnotations = { module = "com.squareup.anvil:annotations", version.ref = "anvil" }
anvilCompiler = { module = "com.squareup.anvil:compiler-api", version.ref = "anvil" }
anvilCompilerUtils = { module = "com.squareup.anvil:compiler-utils", version.ref = "anvil" }
anvilGradle = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }
autoServiceAnnotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
autoServiceCompiler = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mavenPublish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublish" }
